name: ChitChat
version: '${project.version}'
main: me.youhavetrouble.chitchat.ChitChat
api-version: '1.20'
load: POSTWORLD
authors: [YouHaveTrouble]
description: Just a chat plugin
website: youhavetrouble.me
folia-supported: true
softdepend:
  - PlaceholderAPI
permissions:
  chitchat.deletemessage:
    description: Allows for deletion of messages
    default: op
  chitchat.color:
    description: Allows you to use color tags in chat
    default: op
  chitchat.rainbow:
    description: Allows you to use rainbow tags in chat
    default: op
  chitchat.gradient:
    description: Allows you to use gradient tags in chat
    default: op
  chitchat.font:
    description: Allows you to use font tags in chat
    default: op
  chitchat.format:
    description: Allows you to use all formatting in chat
    default: op
    children:
      chitchat.format.bold: true
      chitchat.format.italic: true
      chitchat.format.underline: true
      chitchat.format.strikethrough: true
      chitchat.format.obfuscated: true
  chitchat.format.bold:
    description: Allows you to use bold tags in chat
    default: false
  chitchat.format.italic:
    description: Allows you to use italic tags in chat
    default: false
  chitchat.format.underline:
    description: Allows you to use underline tags in chat
    default: false
  chitchat.format.strikethrough:
    description: Allows you to use strikethrough tags in chat
    default: false
  chitchat.format.obfuscated:
    description: Allows you to use obfuscated tags in chat
    default: false
